### ISSUE TITLE
docs typo

### ISSUE THREAD

**Issue by wwj718** [croquet/microverse-builder#2]
hi @yoshikiohshima,

I'm learning docs recently, I'll give my feedback on the reading process.

1.
[CardSpec dataScale](https://github.com/croquet/microverse-builder/blob/main/docs/CardSpec.md#description-4)

> A 3D model loaded as part of a card may have its own scale. You can use \*dataTranslation\* as a "one time" fix to \*translate\* the 3D model when loading.

2.
[CardSpec Visual Properties width and height](https://github.com/croquet/microverse-builder/blob/main/docs/CardSpec.md#name-11)

> ###Description (missed a space)

3.
[Development persistence](https://github.com/croquet/microverse-builder/blob/main/docs/Development.md#persistence)

> Also note that the start file, either in `.js` or `.json, is used only once to initialize the session. Any changes to the file after starting the world will not have any effects if you open the same Croquet Microvese session, which is specified by the `?q=` URL parameter.

**Comment by yoshikiohshima** [comment]
Thanks!

**Comment by wwj718** [comment]
😄
