### ISSUE TITLE
How to make DriveActor work ?

### ISSUE THREAD

**Issue by wwj718** [croquet/microverse-builder#3]
I add  Drive action to a object（in the Property Sheet）, then the object start running in circles, but I can't  use the arrow keys to control it. Maybe I missed something.

**Comment by yoshikiohshima** [comment]
Thanks for reporting. I took out some features to make it fit in the code editor in the world but it is somewhat in the inconsistent state.  The main problem is that there is a "click-to-focus" global policy for keyboard but I took out the eventhandler from DriveActor that tells the system that it is interested in pointerDown event.

What needs to happen is to add a line:

        this.addEventListener("pointerDown", "nop");

to the setup() of DriveActor. nop() is a method that does nothing. With this code, you should be able to click on the object you attach Drive module to, and use cursor keys.

(I'll fix it.)

**Comment by wwj718** [comment]
Thank you for the explanation and guidance , it works for me :-)
